/*
 * AddressDataMange.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui.address;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.liao.entity.Address;
import com.liao.entity.User;
import com.liao.factory.ObjectFactory;
import com.liao.service.AddressService;
import com.liao.ui.Management;
import com.liao.ui.user.Personalcenter;
import com.liao.util.ResJson;

/**
 * 地址管理
 *
 * @author __USER__
 */
@SuppressWarnings("all")
public class AddressDataMange extends javax.swing.JFrame {
    AddressService addressService = (AddressService) ObjectFactory.getBean("AddressService");
    private User u;

    /**
     * Creates new form AddressDataMange
     */
    public AddressDataMange() {
        initComponents();
    }

    public AddressDataMange(User u) {
        this.u = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        PhoneText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        RemarksText = new javax.swing.JTextField();
        SelectButt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        AllNum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pageSizeComBox = new javax.swing.JComboBox();
        onButt = new javax.swing.JButton();
        totalPageLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        currentPage = new javax.swing.JLabel();
        under = new javax.swing.JButton();
        jumpText = new javax.swing.JTextField();
        jumpButt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel1.setText("\u59d3\u540d");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel2.setText("\u7535\u8bdd");

        NameText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        PhoneText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel3.setText("\u5730\u5740");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel4.setText("\u5907\u6ce8");

        AddressText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        RemarksText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        SelectButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        SelectButt.setText("\u67e5\u8be2");
        SelectButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectButtMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jButton1.setText("\u8fd4\u56de");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        AddressTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{

        }, new String[]{"编号", "姓名", "地址", "电话", "备注"}) {
            Class[] types = new Class[]{java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[]{false, false, false, false, false};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(AddressTable);

        jLabel5.setText("\u603b\u6761\u6570");

        AllNum.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AllNum.setText("1");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel7.setText("\u6bcf\u9875\u5c55\u793a");

        pageSizeComBox.setFont(new java.awt.Font("微软雅黑", 0, 15));
        pageSizeComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"5", "10", "15", "20"}));

        onButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        onButt.setText("\u4e0a\u4e00\u9875");
        onButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onButtMouseClicked(evt);
            }
        });

        totalPageLabel.setFont(new java.awt.Font("微软雅黑", 0, 15));
        totalPageLabel.setText("1");

        jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel9.setText("/");

        currentPage.setFont(new java.awt.Font("微软雅黑", 0, 15));
        currentPage.setText("1");

        under.setFont(new java.awt.Font("微软雅黑", 0, 15));
        under.setText("\u4e0b\u4e00\u9875");
        under.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                underMouseClicked(evt);
            }
        });

        jumpText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jumpText.setText("0");

        jumpButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jumpButt.setText("\u8df3\u8f6c");
        jumpButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumpButtMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel6.setText("\u7528\u6237\u5730\u5740\u7ba1\u7406");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGap(88, 88, 88).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                layout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(AllNum).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                        pageSizeComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(141, 141, 141)
                                        .addComponent(onButt).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(totalPageLabel).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel9).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currentPage).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(under).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE).addComponent(jumpButt).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jumpText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel2).addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(PhoneText).addComponent(NameText,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235,
                                        Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3).addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(AddressText).addComponent(RemarksText,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(SelectButt).addComponent(jButton1)))).addGap(42, 42, 42)).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(458, Short.MAX_VALUE).addComponent(jLabel6).addGap(436, 436, 436)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGap(22, 22, 22).addComponent(jLabel6).addGap(21, 21, 21).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
                                layout.createSequentialGroup().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(SelectButt).addComponent(AddressText,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(36, 36, 36).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(jButton1).addComponent(RemarksText,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addGroup(
                                layout.createSequentialGroup().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(42, 42, 42).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(12, 12, 12).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(AllNum).addComponent(jLabel7).addComponent(pageSizeComBox,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jumpButt).addComponent(
                                jumpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(onButt)
                                .addComponent(totalPageLabel).addComponent(jLabel9).addComponent(currentPage).addComponent(under)).addContainerGap(31, Short.MAX_VALUE)));
        wick();
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    /**
     * 查询按钮
     */
    private void SelectButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取查询的数据
        Address address = getAddressInfo();
        // 		获取当前每页展示多少条
        int pageSize = Integer.parseInt(((String) this.pageSizeComBox.getSelectedItem()));
        //		初始化表格
        AddressTable(1, pageSize, address);
        //		加载条数
        initUsersGrid(address);
    }

    private void wick() {
        //		初始化表格
        AddressTable(1, 5, null);
        //				加载条数
        initUsersGrid(null);
    }

    /**
     * 返回
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        new Management(u).setVisible(true);
        this.dispose();
    }

    /**
     * 跳转按钮
     */
    private void jumpButtMouseClicked(java.awt.event.MouseEvent evt) {
        String str = this.jumpText.getText();
        if (!str.matches("^[1-9][0-9]*$")) {
            JOptionPane.showMessageDialog(null, "跳转页数不合法");
            return;
        }
        int jump = Integer.parseInt(str);
        // 		获取pageSize
        int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());

        // 		获取输入框的信息
        Address address = getAddressInfo();

        int curren = Integer.parseInt(currentPage.getText());
        if (jump > curren) {
            JOptionPane.showMessageDialog(null, "当前页数不存在");
        } else {
            this.totalPageLabel.setText(jump + "");
            // 			刷新表格
            AddressTable(jump, pageSize, address);
            //			刷新条数
            initUsersGrid(address);
        }
    }

    /**
     * 下一页
     *
     * @param evt
     */
    private void underMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取第一个数值
        int pageNum = Integer.parseInt(this.totalPageLabel.getText());
        //		获取第二个数值
        int totalNum = Integer.parseInt(this.currentPage.getText());

        if (pageNum >= totalNum) {

            JOptionPane.showMessageDialog(null, "当前已经是最后一页 ");

        } else {
            pageNum = pageNum + 1;
            //	 		设置当前页数
            this.totalPageLabel.setText(pageNum + "");
            // 			获取pageSize
            int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
            // 			获取输入框的信息
            Address address = getAddressInfo();
            //			刷新表格
            AddressTable(pageNum, pageSize, address);
            //			刷新条数
            initUsersGrid(address);

        }
    }

    /**
     * 上一页
     */
    private void onButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取第一个数值
        int pageNum = Integer.parseInt(this.totalPageLabel.getText());
        //		获取第二个数值
        int totalNum = Integer.parseInt(this.currentPage.getText());
        if (pageNum <= 1) {
            JOptionPane.showMessageDialog(null, "当前已经是第一页 ");
        } else {
            pageNum = pageNum - 1;
            // 			设置当前页数
            this.totalPageLabel.setText(pageNum + "");
            // 			获取pageSize
            int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
            // 			获取输入框的信息
            Address address = getAddressInfo();
            //			刷新表格
            AddressTable(pageNum, pageSize, address);
            //			刷新条数
            initUsersGrid(address);
        }
    }

    /**
     * 清空输入框
     */
    private void clearInput() {
        //		名称
        this.NameText.setText("");
        //		电话
        this.PhoneText.setText("");
        //		备注
        this.RemarksText.setText("");
        //		地址
        this.AddressText.setText("");
    }

    /**
     * 加载条数
     */
    public void initUsersGrid(Address address) {
        //		调用方法，查询符合条件的数据数量
        //		如果goods等于空，则查询全部
        double count = addressService.selectAddressouny(address, null);
        //		获取当前每页展示多少条数据
        double pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
        //		用总条数计算页数
        int totalCount = (int) (Math.ceil(count / pageSize));
        //		总条数赋值
        this.AllNum.setText((int) count + "");
        //		总页数赋值
        this.currentPage.setText(totalCount + "");
    }

    /**
     * 初始化表格
     */
    public void AddressTable(int pageNum, int pageSize, Address address) {
        ResJson jesc = new ResJson();
        //		调用查询方法
        jesc = addressService.selectAddressByLimit(pageNum, pageSize, address, null);
        //		判断是否有数据
        if (jesc.getSub()) {
            //			获取数据
            List<Address> addressestList = jesc.getList();
            //			获取表格对象
            DefaultTableModel tableModel = (DefaultTableModel) this.AddressTable.getModel();
            tableModel.setRowCount(0);
            //			遍历数据存入表格
            for (Address addre : addressestList) {
                Vector rowData = new Vector();
                //				所属用户ID
                rowData.add(addre.getId());
                //				用户名称
                rowData.add(addre.getName());
                //				地址
                rowData.add(addre.getUseraddress());
                //				电话
                rowData.add(addre.getPhone());
                //				备注
                rowData.add(addre.getRemarks());
                tableModel.addRow(rowData);
            }
        }

    }

    /**
     * 获取输入框文本
     *
     * @return
     */
    public Address getAddressInfo() {
        Address address = new Address();
        //		姓名
        String NameText = this.NameText.getText();
        address.setName(NameText);
        //		地址
        String AddressText = this.AddressText.getText();
        address.setUseraddress(AddressText);
        //		电话
        String PhoneText = this.PhoneText.getText();
        address.setPhone(PhoneText);
        //		备注
        String RemarksText = this.RemarksText.getText();
        address.setRemarks(RemarksText);

        return address;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressDataMange().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JTable AddressTable;
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel AllNum;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JTextField RemarksText;
    private javax.swing.JButton SelectButt;
    private javax.swing.JLabel currentPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jumpButt;
    private javax.swing.JTextField jumpText;
    private javax.swing.JButton onButt;
    private javax.swing.JComboBox pageSizeComBox;
    private javax.swing.JLabel totalPageLabel;
    private javax.swing.JButton under;
    // End of variables declaration//GEN-END:variables

}