/*
 * LoginFrom.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui;

import javax.swing.JOptionPane;

import com.liao.entity.User;
import com.liao.factory.ObjectFactory;
import com.liao.service.UserService;
import com.liao.ui.user.Personalcenter;
import com.liao.ui.user.Registered;
import com.liao.ui.user.UserMangement;
import com.liao.util.ResJson;

/**
 * @author __USER__
 */
@SuppressWarnings("all")
public class LoginFrom extends javax.swing.JFrame {

    private User u;

    /**
     * Creates new form LoginFrom
     */
    public LoginFrom() {
        initComponents();
    }

    public LoginFrom(User user) {
        this.u = user;
        initComponents();
    }

    static UserService userService = (UserService) ObjectFactory
            .getBean("UserService");

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {

        站嘎和哦 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginName = new javax.swing.JTextField();
        loginPwd = new javax.swing.JTextField();
        logButton = new javax.swing.JButton();
        regis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("微软雅黑", 1, 10));

        站嘎和哦.setFont(new java.awt.Font("微软雅黑", 0, 15));
        站嘎和哦.setText("\u5e10\u53f7");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel1.setText("\u5bc6\u7801");

        loginName.setFont(new java.awt.Font("微软雅黑", 0, 15));
        loginName.setText("zhangkang");

        loginPwd.setFont(new java.awt.Font("微软雅黑", 0, 15));
        loginPwd.setText("Zhangkang");
        loginPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPwdActionPerformed(evt);
            }
        });

        logButton.setFont(new java.awt.Font("微软雅黑", 0, 15));
        logButton.setText("\u767b\u5f55");
        logButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logButtonMouseClicked(evt);
            }
        });

        regis.setFont(new java.awt.Font("微软雅黑", 0, 15));
        regis.setText("\u6ce8\u518c");
        regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        logButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        83,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(51, 51,
                                                                        51)
                                                                .addComponent(
                                                                        regis,
                                                                        0,
                                                                        0,
                                                                        Short.MAX_VALUE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(
                                                                                        jLabel1)
                                                                                .addComponent(
                                                                                        站嘎和哦))
                                                                .addGap(31, 31,
                                                                        31)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        loginName,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        89,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(
                                                                                        loginPwd,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        140,
                                                                                        Short.MAX_VALUE))))
                                .addContainerGap(86, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(站嘎和哦)
                                                .addComponent(
                                                        loginName,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(
                                                        loginPwd,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(
                                                        regis,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
                                                        logButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        21,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(95, Short.MAX_VALUE)));
//		如果传入的u不为空则为文本框赋值
//		if(!(u == null)){
//			Assign(u);
//		}
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    /**
     * 注册按钮
     */
    private void regisMouseClicked(java.awt.event.MouseEvent evt) {
        new Registered().setVisible(true);
        this.dispose();
    }

    /**
     * 注册成功后，帐号密码框赋值
     *
     * @param evt
     */
    public void Assign(User user) {
        this.loginName.setText(user.getLoginName());
        this.loginPwd.setText(user.getLoginPwd());
    }

    /**
     * 登陆按钮
     *
     * @param evt
     */
    private void logButtonMouseClicked(java.awt.event.MouseEvent evt) {
//		获取输入框文本
        String name = loginName.getText();
        String pwd = loginPwd.getText();
//		将获取到的文本赋值给user；
        User user = new User();
        user.setLoginName(name);
        user.setLoginPwd(pwd);
//		调用登录方法
        ResJson rejs = userService.login(user);
//		判断登录状态
        if (rejs.getSub()) {
//			登录成功
            User u = (User) rejs.getList().get(0);
            JOptionPane.showMessageDialog(null, rejs.getStr());
            if (Integer.parseInt(u.getLev()) < 5) {
//				普通用户
                new Personalcenter(u).setVisible(true);
                JOptionPane.showMessageDialog(null, "欢迎你" + u.getNikeName());
                this.dispose();
            } else {
//				管理员
                new Management(u).setVisible(true);
                JOptionPane.showMessageDialog(null, "欢迎你" + u.getNikeName());
                this.dispose();
            }
//			登录失败
        } else {
            JOptionPane.showMessageDialog(null, rejs.getStr());
        }
    }

    private void loginPwdActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrom().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logButton;
    private javax.swing.JTextField loginName;
    private javax.swing.JTextField loginPwd;
    private javax.swing.JButton regis;
    private javax.swing.JLabel 站嘎和哦;
    // End of variables declaration//GEN-END:variables

}