/*
 * Management.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui;

import com.liao.entity.User;
import com.liao.ui.address.AddressData;
import com.liao.ui.address.AddressDataMange;
import com.liao.ui.category.CategoryData;
import com.liao.ui.comment.CommentData;
import com.liao.ui.comment.CommentDataMange;
import com.liao.ui.goods.GoodsData;
import com.liao.ui.order.OrderData;
import com.liao.ui.order.OrderDataManage;
import com.liao.ui.shoppingcart.ShoppingCartData;
import com.liao.ui.shoppingcart.ShoppingCartManage;
import com.liao.ui.user.UserMangement;

/**
 * @author __USER__
 */
@SuppressWarnings("all")
public class Management extends javax.swing.JFrame {

    /**
     * Creates new form Management
     */
    private User u;

    public Management() {
        initComponents();
    }

    public Management(User u) {
        this.u = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        UserManagement = new javax.swing.JButton();
        GoodsManagement = new javax.swing.JButton();
        CategoryManagement = new javax.swing.JButton();
        Escbutt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        AddressButt = new javax.swing.JButton();
        ShoppingCartButt = new javax.swing.JButton();
        CommentButt = new javax.swing.JButton();
        OrdersButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserManagement.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserManagement.setText("\u7528\u6237\u7ba1\u7406");
        UserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserManagementMouseClicked(evt);
            }
        });

        GoodsManagement.setFont(new java.awt.Font("微软雅黑", 0, 15));
        GoodsManagement.setText("\u5546\u54c1\u7ba1\u7406");
        GoodsManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoodsManagementMouseClicked(evt);
            }
        });
        GoodsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsManagementActionPerformed();
            }
        });

        CategoryManagement.setFont(new java.awt.Font("微软雅黑", 0, 15));
        CategoryManagement.setText("\u5546\u54c1\u7c7b\u522b");
        CategoryManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryManagementMouseClicked(evt);
            }
        });
        CategoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryManagementActionPerformed(evt);
            }
        });

        Escbutt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        Escbutt.setText("\u9000\u51fa\u5230\u767b\u9646");
        Escbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscbuttMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel1.setText("\u6b22\u8fce\u4f60\uff1a");

        name.setFont(new java.awt.Font("微软雅黑", 0, 15));
        name.setText("0");

        AddressButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AddressButt.setText("\u5730\u5740\u7ba1\u7406");
        AddressButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressButtMouseClicked(evt);
            }
        });

        ShoppingCartButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        ShoppingCartButt.setText("\u8d2d\u7269\u8f66\u7ba1\u7406");
        ShoppingCartButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShoppingCartButtMouseClicked(evt);
            }
        });

        CommentButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        CommentButt.setText("\u8bc4\u8bba\u7ba1\u7406");
        CommentButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommentButtMouseClicked(evt);
            }
        });

        OrdersButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        OrdersButt.setText("\u8ba2\u5355\u7ba1\u7406");
        OrdersButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersButtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(name).addContainerGap()).addGroup(
                layout.createSequentialGroup().addGap(27, 27, 27).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(CategoryManagement, javax.swing.GroupLayout.Alignment.LEADING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE).addComponent(GoodsManagement, javax.swing.GroupLayout.Alignment.LEADING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE).addComponent(UserManagement, javax.swing.GroupLayout.Alignment.LEADING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)).addComponent(Escbutt)).addGap(107, 107, 107).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(AddressButt, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(ShoppingCartButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CommentButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(OrdersButt,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(50, 50, 50)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE).addComponent(name)).addGap(37, 37, 37).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(UserManagement).addComponent(AddressButt)).addGap(18, 18, 18).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(GoodsManagement).addComponent(ShoppingCartButt)).addGap(18, 18, 18).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(CategoryManagement).addComponent(CommentButt)).addGap(18, 18, 18).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(Escbutt).addComponent(OrdersButt)).addGap(69, 69, 69)));
        welcome();
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    /**
     * 订单按钮事件
     *
     * @param evt
     */
    private void OrdersButtMouseClicked(java.awt.event.MouseEvent evt) {
        new OrderDataManage(u).setVisible(true);
        this.dispose();
    }

    /**
     * 评论按钮事件
     *
     * @param evt
     */
    private void CommentButtMouseClicked(java.awt.event.MouseEvent evt) {
        new CommentDataMange(u).setVisible(true);
        this.dispose();
    }

    /**
     * 购物车按钮事件
     *
     * @param evt
     */
    private void ShoppingCartButtMouseClicked(java.awt.event.MouseEvent evt) {
        new ShoppingCartManage(u).setVisible(true);
        this.dispose();
    }

    /**
     * 地址按钮事件
     *
     * @param evt
     */
    private void AddressButtMouseClicked(java.awt.event.MouseEvent evt) {
        new AddressDataMange(u).setVisible(true);
        this.dispose();
    }

    /**
     * 退出到登陆界面
     */
    private void EscbuttMouseClicked(java.awt.event.MouseEvent evt) {
        new LoginFrom(u).setVisible(true);
        this.dispose();
    }

    /**
     * 商品类别管理
     */
    private void CategoryManagementMouseClicked(java.awt.event.MouseEvent evt) {
        new CategoryData(u).setVisible(true);
        this.dispose();
    }

    private void CategoryManagementActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * 商品管理按钮事件
     */
    private void GoodsManagementMouseClicked(java.awt.event.MouseEvent evt) {
        new GoodsData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 用户管理按钮事件
     */
    private void UserManagementMouseClicked(java.awt.event.MouseEvent evt) {
        new UserMangement(u).setVisible(true);
        this.dispose();
    }

    void GoodsManagementActionPerformed() {
    }

    /**
     * 界面左上角姓名初始化
     */
    public void welcome() {
        this.name.setText(u.getNikeName());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton AddressButt;
    private javax.swing.JButton CategoryManagement;
    private javax.swing.JButton CommentButt;
    private javax.swing.JButton Escbutt;
    private javax.swing.JButton GoodsManagement;
    private javax.swing.JButton OrdersButt;
    private javax.swing.JButton ShoppingCartButt;
    private javax.swing.JButton UserManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables

}