/*
 * Personalcenter.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui.user;

import com.liao.entity.Order;
import com.liao.entity.User;
import com.liao.ui.LoginFrom;
import com.liao.ui.address.AddressData;
import com.liao.ui.comment.CommentData;
import com.liao.ui.order.OrderData;

@SuppressWarnings("all")
/**
 * 个人中心
 * @author __USER__
 */
public class Personalcenter extends javax.swing.JFrame {

    /**
     * Creates new form Personalcenter
     */
    private User u;

    public Personalcenter() {
        initComponents();
    }

    public Personalcenter(User user) {
        this.u = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UserLev = new javax.swing.JLabel();
        UserAge = new javax.swing.JLabel();
        UserImg = new javax.swing.JLabel();
        UserSex = new javax.swing.JLabel();
        UserAccount = new javax.swing.JLabel();
        UpdateUserData = new javax.swing.JButton();
        ShoppingButt = new javax.swing.JButton();
        AddressButt = new javax.swing.JButton();
        orderButt = new javax.swing.JButton();
        CommentButt = new javax.swing.JButton();
        EscButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
        jLabel1.setText("\u4e2a\u4eba\u4e2d\u5fc3");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel3.setText("\u4f60\u597d\uff1a");

        UserName.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserName.setText("name");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel4.setText("\u8d26\u53f7\uff1a");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel5.setText("\u7b49\u7ea7\uff1a");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel6.setText("\u5e74\u9f84\uff1a");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel7.setText("\u5934\u50cf\uff1a");

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel8.setText("\u6027\u522b\uff1a");

        UserLev.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserLev.setText("Lev");

        UserAge.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserAge.setText("Age");

        UserImg.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserImg.setText("Img");

        UserSex.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserSex.setText("Sex");

        UserAccount.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UserAccount.setText("Account");

        UpdateUserData.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UpdateUserData.setText("\u7f16\u8f91");
        UpdateUserData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateUserDataMouseClicked(evt);
            }
        });

        ShoppingButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        ShoppingButt.setText("\u8d2d\u7269\u8f66");
        ShoppingButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShoppingButtMouseClicked(evt);
            }
        });

        AddressButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AddressButt.setText("\u5730\u5740");
        AddressButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressButtMouseClicked(evt);
            }
        });

        orderButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        orderButt.setText("\u8ba2\u5355");
        orderButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderButtMouseClicked(evt);
            }
        });

        CommentButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        CommentButt.setText("\u8bc4\u8bba");
        CommentButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommentButtMouseClicked(evt);
            }
        });

        EscButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        EscButt.setText("\u8fd4\u56de");
        EscButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscButtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserSex)
                                .addContainerGap(290, Short.MAX_VALUE))
                .addGroup(
                        layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserLev))
                .addGroup(
                        layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserAge))
                .addGroup(
                        layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserAccount)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel9)))
                .addGroup(
                        layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserImg))
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        UserName))
                                                .addComponent(ShoppingButt))
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addComponent(
                                                                        orderButt)
                                                                .addGap(24, 24,
                                                                        24)
                                                                .addComponent(
                                                                        CommentButt))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(66, 66,
                                                                        66)
                                                                .addComponent(
                                                                        jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        81,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        45, Short.MAX_VALUE)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                false)
                                                .addComponent(
                                                        UpdateUserData,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addComponent(
                                                        AddressButt,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addComponent(
                                                        EscButt,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel3)
                                                                                .addComponent(
                                                                                        UserName)
                                                                                .addComponent(
                                                                                        jLabel1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        48,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(
                                                                        jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel4)
                                                                                .addComponent(
                                                                                        jLabel9)
                                                                                .addComponent(
                                                                                        UserAccount))
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel8)
                                                                                .addComponent(
                                                                                        UserSex))
                                                                .addGap(30, 30,
                                                                        30)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel5)
                                                                                .addComponent(
                                                                                        UserLev))
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel6)
                                                                                .addComponent(
                                                                                        UserAge))
                                                                .addGap(29, 29,
                                                                        29)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(
                                                                                        jLabel7)
                                                                                .addComponent(
                                                                                        UserImg)))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        UpdateUserData)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(
                                                                        EscButt)))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        50, Short.MAX_VALUE)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ShoppingButt)
                                                .addComponent(AddressButt)
                                                .addComponent(orderButt)
                                                .addComponent(CommentButt))));
        initializationUserData();
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    /**
     * 返回登录界面
     *
     * @param evt
     */
    private void EscButtMouseClicked(java.awt.event.MouseEvent evt) {
        new LoginFrom(u).setVisible(true);
        this.dispose();
    }

    /**
     * 订单按钮
     */
    private void orderButtMouseClicked(java.awt.event.MouseEvent evt) {
        new OrderData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 评论按钮
     *
     * @param evt
     */
    private void CommentButtMouseClicked(java.awt.event.MouseEvent evt) {
        new CommentData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 跳转到地址界面
     */
    private void AddressButtMouseClicked(java.awt.event.MouseEvent evt) {
        new AddressData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 购物车单机事件
     */
    private void ShoppingButtMouseClicked(java.awt.event.MouseEvent evt) {
        new com.liao.ui.shoppingcart.ShoppingCartData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 用户界面编辑按钮事件
     */
    private void UpdateUserDataMouseClicked(java.awt.event.MouseEvent evt) {
        new UserEditedData(u).setVisible(true);
        this.dispose();
    }

    /**
     * 初始化用户界面用户信息
     */
    public void initializationUserData() {
        this.UserName.setText(u.getNikeName());
        this.UserAge.setText(u.getAge());
        this.UserLev.setText(u.getLev());
        this.UserAccount.setText(u.getLoginName());
        this.UserSex.setText(u.getSex());
        this.UserImg.setText(u.getImg());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalcenter().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton AddressButt;
    private javax.swing.JButton CommentButt;
    private javax.swing.JButton EscButt;
    private javax.swing.JButton ShoppingButt;
    private javax.swing.JButton UpdateUserData;
    private javax.swing.JLabel UserAccount;
    private javax.swing.JLabel UserAge;
    private javax.swing.JLabel UserImg;
    private javax.swing.JLabel UserLev;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel UserSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton orderButt;
    // End of variables declaration//GEN-END:variables

}