/*
 * UserEditedData.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui.user;

import javax.swing.JOptionPane;

import com.liao.entity.User;
import com.liao.factory.ObjectFactory;
import com.liao.service.UserService;
import com.liao.ui.LoginFrom;
import com.liao.util.ResJson;

/**
 * @author __USER__
 */

/**
 * 用户信息修改界面
 */
@SuppressWarnings("all")
public class UserEditedData extends javax.swing.JFrame {
    //	使用多态指向子类
    static UserService userService = (UserService) ObjectFactory.getBean("UserService");
    /** Creates new form UserEditedData */
    private User u;

    public UserEditedData() {
        initComponents();
    }

    public UserEditedData(User user) {
        this.u = user;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        LogPwdText = new javax.swing.JTextField();
        SexText = new javax.swing.JComboBox();
        AgeText = new javax.swing.JTextField();
        ImgText = new javax.swing.JTextField();
        UpdateUserData = new javax.swing.JButton();
        Esc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel1.setText("\u7f16\u8f91\u4e2a\u4eba\u4fe1\u606f");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel2.setText("\u59d3\u540d");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel4.setText("\u5bc6\u7801");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel6.setText("\u6027\u522b");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel7.setText("\u5e74\u9f84");

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel8.setText("\u5934\u50cf");

        NameText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        LogPwdText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        LogPwdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogPwdTextActionPerformed(evt);
            }
        });

        SexText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        SexText.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"男", "女"}));

        AgeText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });

        ImgText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        ImgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgTextActionPerformed(evt);
            }
        });

        UpdateUserData.setFont(new java.awt.Font("微软雅黑", 0, 15));
        UpdateUserData.setText("\u786e\u8ba4\u4fee\u6539");
        UpdateUserData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateUserDataMouseClicked(evt);
            }
        });

        Esc.setFont(new java.awt.Font("微软雅黑", 0, 15));
        Esc.setText("\u53d6\u6d88");
        Esc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscMouseClicked(evt);
            }
        });
        Esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(114, 114, 114).addComponent(jLabel1).addGap(112, 112, 112)).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGap(37, 37, 37).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel4).addComponent(jLabel6).addComponent(jLabel2).addComponent(
                                                jLabel7).addComponent(jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(ImgText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                                .addComponent(NameText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE).addComponent(SexText,
                                                javax.swing.GroupLayout.Alignment.TRAILING, 0, 162, Short.MAX_VALUE).addComponent(LogPwdText,
                                                javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE).addComponent(AgeText,
                                                javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)).addGap(75, 75, 75))).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(Esc, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(UpdateUserData, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                layout.createSequentialGroup().addComponent(UpdateUserData).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(Esc)).addGroup(
                                layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(33, 33, 33).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2)).addGap(30, 30, 30).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(LogPwdText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel4)).addGap(20, 20, 20).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(SexText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))).addGap(18, 18, 18).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                layout.createSequentialGroup().addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(ImgText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8))).addComponent(jLabel7)).addContainerGap(95,
                        Short.MAX_VALUE)));
        initializationUserData();
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    private void ImgTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 返回按钮
     */
    private void EscMouseClicked(java.awt.event.MouseEvent evt) {
        new Personalcenter(u).setVisible(true);
        this.dispose();
    }

    private void EscActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 为修改文本框赋值
     */
    public void wick() {
        initializationUserData();
    }

    private void LogPwdTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 初始化用户界面用户信息
     */
    public void initializationUserData() {
        this.NameText.setText(u.getNikeName());
        this.LogPwdText.setText(u.getLoginPwd());
        this.AgeText.setText(u.getAge());
        this.ImgText.setText(u.getImg());

    }

    /**
     * 获取文本框的信息
     * @return 返回要修改的数据
     */
    public User OBtain() {
        User user = new User();
        //		获取当前用户id
        user.setId(u.getId());
        //		获取姓名
        user.setNikeName(NameText.getText());
        //		获取帐号
        user.setLoginName(u.getLoginName());
        //		获取密码
        String pwd = LogPwdText.getText();

        user.setLoginPwd(pwd);
        //		获取年龄
        user.setAge(AgeText.getText());
        //		获取性别
        user.setSex((String) this.SexText.getSelectedItem());
        //		获取等级
        user.setLev(u.getLev());
        //		获取头像
        String img = ImgText.getText();
        //		如果头像为空，则使用默认
        if (img == null || img.trim().length() < 0) {
            user.setImg("1.jpg");
        } else {
            user.setImg(ImgText.getText());
        }
        //		返回数据
        return user;

    }

    /**
     * 确认修改按钮
     */
    private void UpdateUserDataMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取文本框数据
        User user = OBtain();
        //		调用修改方法
        ResJson json = userService.modiUser(user);
        //		判断修改结果
        if (json.getSub()) {
            //			修改成功，界面跳转到登陆
            JOptionPane.showMessageDialog(null, json.getStr());
            new LoginFrom(OBtain()).setVisible(true);
            //			销毁界面
            this.dispose();
        } else {
            //			修改失败，弹出信息
            JOptionPane.showMessageDialog(null, json.getStr());
        }
    }

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserEditedData().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JTextField AgeText;
    private javax.swing.JButton Esc;
    private javax.swing.JTextField ImgText;
    private javax.swing.JTextField LogPwdText;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox SexText;
    private javax.swing.JButton UpdateUserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}