/*
 * comment.java
 *
 * Created on __DATE__, __TIME__
 */

package com.liao.ui.order;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.liao.entity.Address;
import com.liao.entity.Order;
import com.liao.entity.User;
import com.liao.factory.ObjectFactory;
import com.liao.service.AddressService;
import com.liao.service.OrderService;
import com.liao.ui.user.Personalcenter;
import com.liao.util.ResJson;

/**
 * @author __USER__
 */

/**
 * 订单
 */
@SuppressWarnings("all")
public class OrderData extends javax.swing.JFrame {
    OrderService orderService = (OrderService) ObjectFactory.getBean("OrderService");
    /** Creates new form comment */
    private User u;

    public OrderData() {
        initComponents();
    }

    public OrderData(User u) {
        this.u = u;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderidText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        goodsText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        senderText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SelectButt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        AllNum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pageSizeComBox = new javax.swing.JComboBox();
        onButt = new javax.swing.JButton();
        totalPageLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        currentPage = new javax.swing.JLabel();
        underButt = new javax.swing.JButton();
        JumpButt = new javax.swing.JButton();
        jumpText = new javax.swing.JTextField();
        EscButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel1.setText("\u8ba2\u5355");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{

        }, new String[]{"编号", "姓名", "地址", "名称", "价格", "数量", "寄件人", "电话", "备注", "时间"}) {
            Class[] types = new Class[]{java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false, false, false};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordersTable);

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel2.setText("\u7f16\u53f7");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel3.setText("\u59d3\u540d");

        orderidText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        NameText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel4.setText("\u5730\u5740");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel5.setText("\u540d\u79f0");

        AddressText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextActionPerformed(evt);
            }
        });

        goodsText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        goodsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel7.setText("\u7535\u8bdd");

        senderText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        phoneText.setFont(new java.awt.Font("微软雅黑", 0, 15));

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel6.setText("\u5bc4\u4ef6\u4eba");

        SelectButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        SelectButt.setText("\u67e5\u8be2");
        SelectButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectButtMouseClicked(evt);
            }
        });
        SelectButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel8.setText("\u603b\u6761\u6570");

        AllNum.setFont(new java.awt.Font("微软雅黑", 0, 15));
        AllNum.setText("0");

        jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel10.setText("\u6bcf\u9875\u5c55\u793a");

        pageSizeComBox.setFont(new java.awt.Font("微软雅黑", 0, 15));
        pageSizeComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"5", "10", "15", "20"}));

        onButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        onButt.setText("\u4e0a\u4e00\u9875");
        onButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onButtMouseClicked(evt);
            }
        });
        onButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtActionPerformed(evt);
            }
        });

        totalPageLabel.setFont(new java.awt.Font("微软雅黑", 0, 15));
        totalPageLabel.setText("1");

        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jLabel12.setText("/");

        currentPage.setFont(new java.awt.Font("微软雅黑", 0, 15));
        currentPage.setText("1");

        underButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        underButt.setText("\u4e0b\u4e00\u9875");
        underButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                underButtMouseClicked(evt);
            }
        });

        JumpButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        JumpButt.setText("\u8df3\u8f6c");
        JumpButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumpButtMouseClicked(evt);
            }
        });

        jumpText.setFont(new java.awt.Font("微软雅黑", 0, 15));
        jumpText.setText("0");

        EscButt.setFont(new java.awt.Font("微软雅黑", 0, 15));
        EscButt.setText("\u8fd4\u56de");
        EscButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscButtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGap(33, 33, 33).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                layout.createSequentialGroup().addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(AllNum).addGap(46, 46, 46)
                                        .addComponent(jLabel10).addGap(2, 2, 2).addComponent(pageSizeComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addGap(50, 50, 50).addComponent(onButt).addGap(4, 4, 4).addComponent(totalPageLabel).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel12).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currentPage).addGap(4, 4, 4).addComponent(underButt).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                        .addComponent(JumpButt).addGap(18, 18, 18).addComponent(jumpText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
                                        20, 20, 20)).addGroup(
                                layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel3).addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(NameText).addComponent(orderidText,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)).addGap(73, 73, 73).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel4).addComponent(jLabel5)).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(goodsText).addComponent(AddressText,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(80, 80, 80).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6).addComponent(jLabel7)).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(phoneText).addComponent(senderText,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110,
                                        Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(SelectButt).addComponent(EscButt))
                                        .addGap(50, 50, 50)))).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE).addContainerGap()).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(420, Short.MAX_VALUE).addComponent(jLabel1).addGap(375, 375, 375)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
                                layout.createSequentialGroup().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(orderidText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel6).addComponent(senderText,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(SelectButt))
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                                        layout.createSequentialGroup().addGap(38, 38, 38).addGroup(
                                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(NameText,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addComponent(EscButt)))).addGroup(
                                layout.createSequentialGroup().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(38, 38, 38).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(goodsText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel7).addComponent(phoneText,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
                        24, 24, 24).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8).addComponent(AllNum).addComponent(onButt).addComponent(totalPageLabel)
                                .addComponent(jLabel12).addComponent(currentPage).addComponent(underButt).addComponent(jLabel10).addComponent(pageSizeComBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(JumpButt).addComponent(jumpText,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(33, 33, 33)));
        wick();
        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    /**
     * 加载界面
     */
    public void wick() {
        //		初始化表格
        orderTable(1, 5, null);
        //		加载条数
        initOrdersGrid(null);
    }

    /**
     * 返回按钮
     */
    private void EscButtMouseClicked(java.awt.event.MouseEvent evt) {
        new Personalcenter(u).setVisible(true);
        this.dispose();
    }

    /**
     * 查询
     */
    private void SelectButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取查询的数据
        Order order = getOrderInfo();
        // 		获取当前每页展示多少条
        int pageSize = Integer.parseInt(((String) this.pageSizeComBox.getSelectedItem()));
        //		初始化表格
        orderTable(1, pageSize, order);
        //		加载条数
        initOrdersGrid(order);
        //		加载起始页码
        this.totalPageLabel.setText("1");
    }

    /**
     * 跳转
     */
    private void JumpButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取跳转的页码
        String str = this.jumpText.getText();
        //		判断页码是否合法
        if (!str.matches("^[1-9][0-9]*$")) {
            //			不合法弹出错误信息
            JOptionPane.showMessageDialog(null, "跳转页数不合法");
            return;
        }
        //		将合法的值强转为int
        int jump = Integer.parseInt(str);
        // 		获取当前每页展示条数
        int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
        // 		获取输入框的信息
        Order order = getOrderInfo();
        //		获取总页数
        int curren = Integer.parseInt(currentPage.getText());
        //		判断跳转的页数是否大于总页数
        if (jump > curren) {
            //			大于，弹出错误信息
            JOptionPane.showMessageDialog(null, "当前页数不存在");
        } else {
            //			否则跳转
            this.totalPageLabel.setText(jump + "");
            // 			刷新表格
            orderTable(jump, pageSize, order);
        }
    }

    /**
     * 下一页
     */
    private void underButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取当前页数数值
        int pageNum = Integer.parseInt(this.totalPageLabel.getText());
        //		获取总页数数值
        int totalNum = Integer.parseInt(this.currentPage.getText());
        //		判断当前页数是否大于等于总页数
        if (pageNum >= totalNum) {
            //			弹出错误信息
            JOptionPane.showMessageDialog(null, "当前已经是最后一页 ");
            //			否则当前页数加一
        } else {
            pageNum = pageNum + 1;
            // 			赋值给当前页数
            this.totalPageLabel.setText(pageNum + "");
            // 			获取获取当前页展示条数
            int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
            // 			获取输入框的信息
            Order order = getOrderInfo();
            //			刷新表格
            orderTable(pageNum, pageSize, order);
            //			刷新条数
            initOrdersGrid(order);
        }
    }

    /**
     * 上一页
     */
    private void onButtMouseClicked(java.awt.event.MouseEvent evt) {
        //		获取当前页数数值
        int pageNum = Integer.parseInt(this.totalPageLabel.getText());
        //		获取总页数数值
        int totalNum = Integer.parseInt(this.currentPage.getText());
        //		判断当前页数是否小于等于1
        if (pageNum <= 1) {
            //			否则当前页数节减一
            JOptionPane.showMessageDialog(null, "当前已经是第一页 ");
        } else {
            // 			赋值给当前页数
            pageNum = pageNum - 1;
            // 			获取获取当前页展示条数
            this.totalPageLabel.setText(pageNum + "");
            // 			获取pageSize
            int pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
            // 			获取输入框的信息
            Order order = getOrderInfo();
            //			刷新表格
            orderTable(pageNum, pageSize, order);
            //			刷新条数
            initOrdersGrid(order);
        }
    }

    private void onButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void goodsTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void AddressTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    void NameTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 清空输入框
     */
    private void clearInput() {
        //		订单编号
        this.orderidText.setText("");
        //		姓名
        this.NameText.setText("");
        //		地址
        this.AddressText.setText("");
        //		商品名称
        this.goodsText.setText("");
        //		电话
        this.phoneText.setText("");
        //		寄件人
        this.senderText.setText("");
    }

    /**
     * 加载条数
     */
    public void initOrdersGrid(Order order) {
        //		调用方法，查询符合条件的数据数量
        double count = orderService.selectOrderouny(order, u);
        //		获取当前每页展示多少条数据
        double pageSize = Integer.parseInt((String) this.pageSizeComBox.getSelectedItem());
        //		用总条数计算页数
        int totalCount = (int) (Math.ceil(count / pageSize));
        //		总条数赋值
        this.AllNum.setText((int) count + "");
        //		总页数赋值
        this.currentPage.setText(totalCount + "");
    }

    /**
     * 初始化表格
     */
    public void orderTable(int pageNum, int pageSize, Order order) {
        //		存储结果
        ResJson jesc = new ResJson();
        //		调用查询方法
        jesc = orderService.selectOrderByLimit(pageNum, pageSize, order, u);
        //		判断结果
        if (jesc.getSub()) {
            //			有结果，获取集合
            //			获取数据
            List<Order> orderList = jesc.getList();
            //			获取表格对象
            DefaultTableModel tableModel = (DefaultTableModel) this.ordersTable.getModel();
            tableModel.setRowCount(0);
            //			遍历数据存入表格
            for (Order orders : orderList) {
                Vector rowData = new Vector();
                //				订单编号
                rowData.add(orders.getNumbering());
                //				用户姓名
                rowData.add(orders.getUserName());
                //				地址
                rowData.add(orders.getUseraddress());
                //				商品名称
                rowData.add(orders.getGoodsName());
                //				价格
                rowData.add(orders.getPrice());
                //				数量
                rowData.add(orders.getQuantity());
                //				寄件人
                rowData.add(orders.getStore());
                //				电话
                rowData.add(orders.getPhone());
                //				备注
                rowData.add(orders.getRemarks());
                //				时间
                rowData.add(orders.getTimes());
                //				存入表格
                tableModel.addRow(rowData);
            }
        }

    }

    /**
     * 获取输入框文本
     * @return 返回文本框的数据
     */
    public Order getOrderInfo() {
        Order order = new Order();
        //		获取ID
        order.setUserID(u.getId());
        //		订单编号
        String orderidText = this.orderidText.getText();
        order.setNumbering(orderidText);
        //		姓名
        String NameText = this.NameText.getText();
        order.setUserName(NameText);
        //		地址
        String AddressText = this.AddressText.getText();
        order.setUseraddress(AddressText);
        //		商品名称
        String goodsText = this.goodsText.getText();
        order.setGoodsName(goodsText);
        //		电话
        String PhoneText = this.phoneText.getText();
        order.setPhone(PhoneText);
        //		寄件人
        String senderText = this.senderText.getText();
        order.setStore(senderText);
        //		返回获取到的值
        return order;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderData().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel AllNum;
    private javax.swing.JButton EscButt;
    private javax.swing.JButton JumpButt;
    private javax.swing.JTextField NameText;
    private javax.swing.JButton SelectButt;
    private javax.swing.JLabel currentPage;
    private javax.swing.JTextField goodsText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumpText;
    private javax.swing.JButton onButt;
    private javax.swing.JTextField orderidText;
    private javax.swing.JTable ordersTable;
    private javax.swing.JComboBox pageSizeComBox;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTextField senderText;
    private javax.swing.JLabel totalPageLabel;
    private javax.swing.JButton underButt;
    // End of variables declaration//GEN-END:variables

}